#include "comm.h"
#include "test_bench.h"
#include "stm32l4xx_hal.h"
#include "cmsis_os.h"
#include "usart.h"
#include <string.h>
#include <stdio.h>

/* External UART handle generated by CubeMX */
extern UART_HandleTypeDef huart2;

/* RX poll timeout — short so TX is not held up waiting for incoming bytes */
#define COMM_RX_TIMEOUT_MS  10U

/* TX queue depth — how many outgoing messages can queue up before blocking */
#define COMM_TX_QUEUE_DEPTH 4U

/* -----------------------------------------------------------------------
 * Internal state
 * --------------------------------------------------------------------- */

static osMessageQueueId_t s_tx_queue;

/*
 * Receiver state machine states.
 * The machine resets to WAIT_SOF on any error, exactly as the protocol
 * spec requires.
 */
typedef enum
{
    RX_WAIT_SOF  = 0,
    RX_READ_TAG  = 1,
    RX_READ_LEN  = 2,
    RX_READ_VALUE = 3,
    RX_READ_CHK  = 4
} RxState_t;

typedef struct
{
    RxState_t state;
    uint8_t   tag;
    uint8_t   len;
    uint8_t   value[COMM_MAX_VALUE_LEN];
    uint8_t   value_idx;
    uint8_t   checksum_accum;
} RxFrame_t;

static RxFrame_t s_rx;

/* -----------------------------------------------------------------------
 * UART wrappers — the only two places HAL is called directly.
 * To switch from UART to Ethernet, replace these two functions only.
 * --------------------------------------------------------------------- */

static void comm_send_bytes(const uint8_t *buf, uint16_t len)
{
    HAL_UART_Transmit(&huart2, buf, len, HAL_MAX_DELAY);
}

static HAL_StatusTypeDef comm_recv_byte(uint8_t *byte_out)
{
    return HAL_UART_Receive(&huart2, byte_out, 1U, COMM_RX_TIMEOUT_MS);
}

/* -----------------------------------------------------------------------
 * Frame builder
 * --------------------------------------------------------------------- */

void Comm_SendFrame(uint8_t tag, const uint8_t *value, uint8_t len)
{
    uint8_t  buf[COMM_MAX_FRAME_LEN];
    uint8_t  chk;
    uint8_t  i;
    uint16_t frame_len;

    chk = (uint8_t)(tag + len);

    buf[0] = COMM_SOF;
    buf[1] = tag;
    buf[2] = len;

    for (i = 0U; i < len; ++i)
    {
        buf[3U + i] = value[i];
        chk = (uint8_t)(chk + value[i]);
    }

    buf[3U + len] = chk;
    frame_len     = (uint16_t)(4U + len);

    comm_send_bytes(buf, frame_len);
}

/* -----------------------------------------------------------------------
 * Serialisers — one per outgoing frame type
 * --------------------------------------------------------------------- */

/*
 * Writes a MEASUREMENT BLOCK into buf (12 bytes, little-endian).
 * Called by both the KEEPALIVE and DATA_REPORT serialisers.
 */
static void write_measurement_block(uint8_t *buf, const MonitorData_t *d)
{
    uint32_t ts;
    int16_t  temp;
    uint8_t  i;

    ts   = HAL_GetTick() / 1000U;
    temp = d->temperature;

    /* timestamp: bytes 0-3, little-endian uint32 */
    for (i = 0U; i < 4U; ++i)
    {
        buf[i] = (uint8_t)(ts >> (8U * i));
    }

    /* temperature: bytes 4-5, little-endian int16 */
    buf[4] = (uint8_t)(temp & 0xFF);
    buf[5] = (uint8_t)((temp >> 8) & 0xFF);

    /* humidity: byte 6, uint8 */
    buf[6] = d->humidity;

    /* battery: bytes 7-8, little-endian uint16 */
    buf[7] = (uint8_t)(d->battery & 0xFF);
    buf[8] = (uint8_t)((d->battery >> 8) & 0xFF);

    /* light: bytes 9-10, little-endian uint16 */
    buf[9]  = (uint8_t)(d->light & 0xFF);
    buf[10] = (uint8_t)((d->light >> 8) & 0xFF);

    /* mode: byte 11, uint8 */
    buf[11] = (uint8_t)d->system_mode;
}

static void send_keepalive(const MonitorData_t *d)
{
    uint8_t value[12];

    write_measurement_block(value, d);
    Comm_SendFrame(TAG_KEEPALIVE, value, 12U);
}

static void send_event(const CommEventPayload_t *e)
{
    uint8_t  value[6];
    uint32_t ts;
    uint8_t  i;

    ts = e->timestamp;

    /* event_type: byte 0 */
    value[0] = e->event_type;

    /* detail: byte 1 */
    value[1] = e->detail;

    /* timestamp: bytes 2-5, little-endian uint32 */
    for (i = 0U; i < 4U; ++i)
    {
        value[2U + i] = (uint8_t)(ts >> (8U * i));
    }

    Comm_SendFrame(TAG_EVENT, value, 6U);
}

static void send_time_sync_req(void)
{
    Comm_SendFrame(TAG_TIME_SYNC_REQ, NULL, 0U);
}

/* -----------------------------------------------------------------------
 * Receiver state machine
 * --------------------------------------------------------------------- */

static void rx_reset(void)
{
    s_rx.state          = RX_WAIT_SOF;
    s_rx.tag            = 0U;
    s_rx.len            = 0U;
    s_rx.value_idx      = 0U;
    s_rx.checksum_accum = 0U;
}

static void dispatch_command(uint8_t tag, const uint8_t *value, uint8_t len);

static void rx_feed_byte(uint8_t byte)
{
    switch (s_rx.state)
    {
        case RX_WAIT_SOF:
            if (COMM_SOF == byte)
            {
                s_rx.state = RX_READ_TAG;
            }
            break;

        case RX_READ_TAG:
            s_rx.tag            = byte;
            s_rx.checksum_accum = byte;
            s_rx.state          = RX_READ_LEN;
            break;

        case RX_READ_LEN:
            s_rx.len             = byte;
            s_rx.checksum_accum  = (uint8_t)(s_rx.checksum_accum + byte);
            s_rx.value_idx       = 0U;
            s_rx.state           = (0U == byte) ? RX_READ_CHK : RX_READ_VALUE;
            break;

        case RX_READ_VALUE:
            s_rx.value[s_rx.value_idx] = byte;
            s_rx.checksum_accum = (uint8_t)(s_rx.checksum_accum + byte);
            ++s_rx.value_idx;

            if (s_rx.value_idx >= s_rx.len)
            {
                s_rx.state = RX_READ_CHK;
            }
            break;

        case RX_READ_CHK:
            if (byte == s_rx.checksum_accum)
            {
                dispatch_command(s_rx.tag, s_rx.value, s_rx.len);
            }
            rx_reset();
            break;

        default:
            rx_reset();
            break;
    }
}

/* -----------------------------------------------------------------------
 * Command dispatch
 * --------------------------------------------------------------------- */

static void dispatch_command(uint8_t tag, const uint8_t *value, uint8_t len)
{
    uint8_t  time_value[4];
    uint32_t ts;
    uint8_t  i;

    (void)value;
    (void)len;

    switch (tag)
    {
        case TAG_SET_CONFIG:
            /* Stage 6: pass to Config module. Stub for now. */
            printf("[COMM-RX] SET_CONFIG received (param_id=0x%02X)\r\n",
                   (unsigned)value[0]);
            break;

        case TAG_SET_TIME:
            /* Stage 6: set RTC. Stub for now. */
            printf("[COMM-RX] SET_TIME received\r\n");
            break;

        case TAG_GET_TIME:
            /* Respond immediately with current tick-based timestamp */
            ts = HAL_GetTick() / 1000U;

            for (i = 0U; i < 4U; ++i)
            {
                time_value[i] = (uint8_t)(ts >> (8U * i));
            }

            Comm_SendFrame(TAG_TIME_REPORT, time_value, 4U);
            break;

        case TAG_GET_DATA_RANGE:
            /* Stage 6: query SD card and stream DATA_ITEMs. Stub for now. */
            printf("[COMM-RX] GET_DATA_RANGE received\r\n");
            /* Send empty end-of-stream marker */
            Comm_SendFrame(0x81U, NULL, 0U);
            break;

        case TAG_GET_EVENTS_RANGE:
            /* Stage 6: query SD card and stream EVENT_ITEMs. Stub for now. */
            printf("[COMM-RX] GET_EVENTS_RANGE received\r\n");
            /* Send empty end-of-stream marker */
            Comm_SendFrame(0x82U, NULL, 0U);
            break;

        default:
            printf("[COMM-RX] Unknown tag 0x%02X — discarded\r\n",
                   (unsigned)tag);
            break;
    }
}

/* -----------------------------------------------------------------------
 * Public functions
 * --------------------------------------------------------------------- */

void Comm_Init(void)
{
    s_tx_queue = osMessageQueueNew(COMM_TX_QUEUE_DEPTH,
                                   sizeof(CommMsg_t),
                                   NULL);
    rx_reset();
}

osMessageQueueId_t Comm_GetTxQueueHandle(void)
{
    return s_tx_queue;
}

void Comm_Task(void *argument)
{
    CommMsg_t msg;
    osStatus_t status;
    uint8_t    rx_byte;

    (void)argument;

    for (;;)
    {
        /* --- TX: drain one message from the queue if available --- */
        status = osMessageQueueGet(s_tx_queue,
                                   &msg,
                                   NULL,
                                   0U);

        if (osOK == status)
        {
            switch (msg.type)
            {
                case COMM_MSG_KEEPALIVE:
                    send_keepalive(&msg.payload.monitor);
                    break;

                case COMM_MSG_EVENT:
                    send_event(&msg.payload.event);
                    break;

                case COMM_MSG_TIME_SYNC_REQ:
                    send_time_sync_req();
                    break;

                default:
                    break;
            }
        }

        /* --- RX: poll for one incoming byte --- */
        if (HAL_OK == comm_recv_byte(&rx_byte))
        {
            rx_feed_byte(rx_byte);
        }
        else
        {
            /* Nothing to send and no byte received — yield to other tasks */
            osDelay(1U);
        }
    }
}